"""add customer_image

Revision ID: 939f87f778d2
Revises: 3af95f233bfd
Create Date: 2026-03-27 15:13:07.033845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939f87f778d2'
down_revision = '3af95f233bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_image')
    # ### end Alembic commands ###
